FROM arm32v7/node:12
MAINTAINER Klaus Gamauf <kg@w4it.at>

WORKDIR /app

COPY package.json /app/
COPY yarn.lock /app/

RUN yarn install --production && yarn cache clean

COPY . /app

ENV NODE_ENV production
ENTRYPOINT ["node", "/app/bin/lt.js"]
